# Generated by Django 5.2.8 on 2025-11-11 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(help_text="Identifier used in templates, e.g. {% draw_menu 'main-menu' %}", unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('named_url', models.CharField(blank=True, help_text='Name of a URL pattern (takes precedence over direct URL).', max_length=200)),
                ('url', models.CharField(blank=True, help_text='Absolute or relative URL when named URL is not used.', max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menus.menu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menus.menuitem')),
            ],
            options={
                'verbose_name': 'Menu item',
                'verbose_name_plural': 'Menu items',
                'ordering': ('menu', 'parent__id', 'position', 'title'),
                'constraints': [
                    models.CheckConstraint(
                        check=(
                            (models.Q(named_url__exact='') & ~models.Q(url__exact=''))
                            | (~models.Q(named_url__exact='') & models.Q(url__exact=''))
                        ),
                        name='menus_menuitem_single_target',
                    )
                ],
            },
        ),
    ]
